Add application call transaction
provable-things/rust-algorand pull request #1
Opened 2022-05-24 16:24 UTC by oliviera9

2022-05-26 20:28 UTC, oliviera9 commented
Fixes #4

2022-05-27 10:02 UTC, gskapka requested changes
See inline comments.

2022-05-27 10:02 UTC, gskapka commented on src/algorand_transactions/asset_transfer_transaction.rs
> +        );
I see that `to_tx_id` just calls the underlying `to_id` transaction method. 

As such, of course we expect these to be the same. 

My question is, why do we have the two methods? Do we need the `to_tx_id` on the signed tx object?

2022-05-27 10:02 UTC, gskapka commented on src/algorand_transactions/pay_transaction.rs
> +    }
I see this is from the `maybe_get_amount` fxn from the `asset_transfer_transaction` mod, where this weird response from the indexer was a problem.

However for this payment tx, isn't the utni always algos? And have we ever seen the same issue for algos? Do we have a sample to test it against?

2022-05-27 10:02 UTC, gskapka commented on src/algorand_transactions/transaction.rs
> +}
Missing newline.

2022-05-27 10:02 UTC, gskapka commented on src/algorand_transactions/transaction.rs
> +impl AsRef<[u8]> for AppArgument {
:+1:

2022-05-27 10:02 UTC, gskapka commented on src/algorand_transactions/transaction.rs
> -    #[serde(rename(serialize = "group"))]
Hahah oops - good spot!

2022-05-27 10:02 UTC, gskapka commented on src/algorand_transactions/transaction.rs
> +    // These fields are retained when building tx from JSON
If this is not a doc comment (ie, with three slashes), and thus is just a note to any developer reading this, please could you prefix it with `NOTE:` to make that clear.

2022-05-27 10:02 UTC, gskapka commented on src/algorand_transactions/transaction.rs
> +    pub close_amount: Option<u64>,
Missing new lines.

2022-05-27 10:02 UTC, gskapka commented on src/algorand_transactions/transaction.rs
> +                Some(sender) if keys.to_address()? != *sender => Some(keys.to_address()?),
You've two calls converting the `keys.to_address()?` here, and since the unwrapping is costly, please factor it out so we only have to do it once.

2022-05-27 10:02 UTC, gskapka commented on src/algorand_transactions/transaction.rs
> +            // TODO: assign correct value to these
???

2022-05-27 10:02 UTC, gskapka commented on src/algorand_transactions/transaction.rs
> +            },
You can make this much more readable by having the `to_application_transaction_json` method return a `Result<Option<ApplicationTransactionJson>>`, leaving this line to look like:

```suggestion
            application_transaction: self.to_application_transaction_json()?,
```

That would make more sense than this match + match guard set up.

2022-05-27 10:02 UTC, gskapka commented on src/algorand_transactions/transaction.rs
> +    fn to_application_transaction_json(&self) -> Result<ApplicationTransactionJson> {
Per above comment, in here, create the json, then check if it's empty before returning either `Ok(Some(json))` or `Ok(None)`

2022-05-27 10:02 UTC, gskapka commented on src/algorand_transactions/application_transaction.rs
> +    /// Application Noop call
Please add more lines to explain what this is in the doc comments, for users of this library, since this is a publicly exported method.

2022-05-27 10:02 UTC, gskapka commented on src/algorand_transactions/application_transaction.rs
> +#[cfg(test)]
Great work on the thorough tests here!! :+1:

2022-05-27 12:35 UTC, oliviera9 commented on src/algorand_transactions/application_transaction.rs
> +#[cfg(test)]
Thanks!!!

2022-05-27 12:56 UTC, oliviera9 commented on src/algorand_transactions/transaction.rs
> +impl AsRef<[u8]> for AppArgument {
I cannot find a reference about this syntax (taken from algonaut):
```rust
 pub struct AppArgument(#[serde(with = "serde_bytes")] pub Vec<u8>); 
```
I suppose this is just a way to define `AppArgument` as an alias of `Vec<u8>`.
Also, I was wondering why I needed to implement `AsRref` as I suppose it should be already available for `Vec<u8>`.

2022-05-27 13:05 UTC, oliviera9 commented on src/algorand_transactions/pay_transaction.rs
> +    }
For sure we will have always algos for this tx, so probably we'll never see this problem. With u64::MAX being 18_446_744_073_709_551_615, and the max supply being 10 billion Algos, even considering the 6 decimals, the value will be never reached for a tx.
I think I could always return `json_value.as_u64()`.

2022-05-27 13:08 UTC, oliviera9 commented on src/algorand_transactions/asset_transfer_transaction.rs
> +        );
Do you mean we could maintain `to_id()` only and calculate the hash from the inner unsigned tx?
For instance, both functions were added by you.

2022-05-27 13:20 UTC, gskapka commented on src/algorand_transactions/asset_transfer_transaction.rs
> +        );
Yeah, I don't see why we have it twice, so let's just maintain the one.

> For instance, both functions were added by you.

:rofl: I was afraid of that. Expect similar questionable practices given the speed and duress the library was built under!

2022-05-27 13:20 UTC, gskapka commented on src/algorand_transactions/pay_transaction.rs
> +    }
^ agreed. Let's change it to your suggestion in that case.

2022-05-27 13:24 UTC, gskapka commented on src/algorand_transactions/transaction.rs
> +impl AsRef<[u8]> for AppArgument {
You're right that AsRef should already be available for `Vec<u8>`, but `Vec<u8>` and `[u8]` are not the same, hence you having to manually derive this. Manually deriving traits like this is super common though, and no issue at all.

2022-05-27 15:38 UTC, oliviera9 commented on src/algorand_transactions/asset_transfer_transaction.rs
> +        );
Ah, the `transaction` field is private. Shall I add a new getter function? on which result we can call `to_id`...

2022-05-27 15:42 UTC, oliviera9 commented on src/algorand_transactions/transaction.rs
> +            // TODO: assign correct value to these
Yeah, I left the comment even after implementing the missing part... Removed

2022-05-27 15:47 UTC, oliviera9 commented on src/algorand_transactions/transaction.rs
> +    fn to_application_transaction_json(&self) -> Result<ApplicationTransactionJson> {
Nice!

2022-05-27 15:47 UTC, oliviera9 commented on src/algorand_transactions/transaction.rs
> +            },
Done

2022-05-27 17:06 UTC, oliviera9 commented on src/algorand_transactions/application_transaction.rs
> +    /// Application Noop call
Done

2022-05-27 17:08 UTC, oliviera9 commented
I renamed application_transaction_json.rs to application_transaction.rs so that application call stuff is contained in a single file like for other txs types.

2022-05-30 11:42 UTC, gskapka commented on src/algorand_transactions/asset_transfer_transaction.rs
> +        );
^ Yes please!

2022-05-30 11:45 UTC, gskapka commented
If you sort to that last unresolved conversation, this PR will be ready :tada:

2022-05-30 12:23 UTC, oliviera9 commented on src/algorand_transactions/asset_transfer_transaction.rs
> +        );
Done!

2022-05-30 12:23 UTC, oliviera9 commented
No more discussions are open! I think we are ready to merge

2022-05-30 13:00 UTC, gskapka submitted a review, later dismissed
LGTM! :+1:

2022-05-30 13:04 UTC, merged